services:
  nuernbergklima:
    build:
      context: .
      dockerfile: src/nuernbergklima/Dockerfile
    container_name: nuernbergklima-test
    restart: always
    ports:
      - "8061:80"
      - "9444:443"
    environment:
      - NODE_ENV=test
