services:
  the_floor_is_lava:
    build:
      context: ..
      dockerfile: src/11ty_website/Dockerfile
    container_name: climatguard_11ty
    restart: always
    ports:
      - "8070:80"
      - "7443:443"