services:
  the_floor_is_lava:
    build:
      context: ..
      dockerfile: src/nuernbergklima/Dockerfile
    container_name: nuernbergklima
    restart: always
    ports:
      - "8060:80"
      - "8443:443"