name: the_floor_is_lava stage deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: quantum_server
    concurrency:
      group: run_stage
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build and Run Docker image
        run: |
          docker compose -f src/nuernbergklima/docker-compose.yml up -d --build
